---
- hosts: all
  become: true
  tasks:

    - name: install update (ubuntu)
      apt:
        upgrade: yes 
        update_cache: yes 
      when: ansible_distribution == "Ubuntu"

- hosts: web_server 
  become: true 
  tasks:

    - name: install the apache2 and PHP package
      apt: 
        name:
          - apache2
          - libapache2-mod-php
        state: latest 
        
    - name: copy default html file to site
      tags: apache, apache2, files
      copy:
         src: default_site.html
         dest: /var/www/html/index.html
         owner: root
         group: root 
         mode: 0644
    
